#!/usr/bin/env python3
"""
Generate .streamlit/secrets.toml from Railway environment variables.

This script reads GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, GOOGLE_REDIRECT_URI,
and COOKIE_SECRET from environment variables and generates a valid Streamlit
secrets.toml file.

This is necessary because Railway uses environment variables, not secrets.toml files,
but Streamlit's native st.login() expects auth config in st.secrets["auth"] format.
"""
import os
import secrets
import sys
from pathlib import Path


def generate_secrets():
    """Generate .streamlit/secrets.toml from environment variables."""

    # Read from environment variables
    client_id = os.getenv("GOOGLE_CLIENT_ID", "")
    client_secret = os.getenv("GOOGLE_CLIENT_SECRET", "")
    redirect_uri = os.getenv("GOOGLE_REDIRECT_URI",
                             "http://localhost:8501/oauth2callback")
    cookie_secret = os.getenv("COOKIE_SECRET", "")

    # Validate required variables
    if not client_id or not client_secret:
        print(
            "⚠️  Warning: GOOGLE_CLIENT_ID or GOOGLE_CLIENT_SECRET not set", file=sys.stderr)
        print("   Skipping secrets.toml generation", file=sys.stderr)
        return False

    # Generate cookie secret if not provided
    if not cookie_secret:
        cookie_secret = secrets.token_urlsafe(32)
        print(
            "⚠️  COOKIE_SECRET not set as environment variable!", file=sys.stderr)
        print(
            "   Generated a random one — user sessions will be invalidated on next deploy.", file=sys.stderr)
        print(
            f"   To fix: set COOKIE_SECRET={cookie_secret} in Railway environment variables.", file=sys.stderr)
    else:
        print("✅ Using COOKIE_SECRET from environment variable", file=sys.stderr)

    # Create .streamlit directory if it doesn't exist
    streamlit_dir = Path(".streamlit")
    streamlit_dir.mkdir(exist_ok=True)

    # Generate secrets.toml content
    secrets_content = f"""# Auto-generated from Railway environment variables
# Generated by scripts/generate_secrets.py

[auth]
redirect_uri = "{redirect_uri}"
cookie_secret = "{cookie_secret}"
client_id = "{client_id}"
client_secret = "{client_secret}"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
"""

    # Write secrets.toml
    secrets_file = streamlit_dir / "secrets.toml"
    secrets_file.write_text(secrets_content)

    print(f"✅ Generated {secrets_file}", file=sys.stderr)
    print(f"   redirect_uri: {redirect_uri}", file=sys.stderr)
    print(f"   client_id: {client_id[:20]}...", file=sys.stderr)

    return True


if __name__ == "__main__":
    success = generate_secrets()
    sys.exit(0 if success else 1)
